version: "3.8"

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile

        container_name: app

        ports:
            - 4200:4200
            
        volumes:
            - ../workspace:/workspace

        command: /bin/sh -c "while sleep 1000; do :; done"            
